### ISSUE TITLE
Implement saving response body to a file

### ISSUE THREAD

**Issue by mfinelli** [mfinelli/cui#10]
Turn the footer into a textfield to prompt the file name and then write the (raw) response to the file. We'll probably need to implement better error handling in the event that the file can't be opened, or written to, etc and panicing is not really good UX. Since we're (sometimes) coloring the response for display we'll need to keep a copy of it to use for writing the actual raw response.

**Comment by jootd** [comment]
Hi, I started working on this feature  and I think Footer component needs to be tview.Flex  rather than tview.Textview , 
what you think about this change ?

**Comment by mfinelli** [comment]
Yes, I had already thought that it would need to be changed to to Flex so that it can hold a `InputField` as well as the instructions `TextView`. When saving to a file you can set the Flex to the InputField and then when done back to the instructions TextView.

The `cui` app should then probably hold a reference to all of the Footer flex, instructions TextView, and inputField. Let me know if you have any other questions

**Comment by mfinelli** [comment]
Resolved by #19
