### ISSUE TITLE
Add response size (bytes) to view

### ISSUE THREAD

**Issue by mfinelli** [mfinelli/cui#2]
Best place is probably next to the "status" line e.g., "Status: 200, Response size: 400 bytes". It would be nice to make it human readable (with a toggle to raw bytes).

**Comment by jootd** [comment]
Hi, I have question about this issue . Is it right that response size in bytes is 
	body, err := ioutil.ReadAll(res.Body)
        len(body)  // <----

**Comment by mfinelli** [comment]
`len(body)` is probably good enough. In theory we could also read a `Content-Length` header if it exists, but not all webservers or response types will send that header so I think it's better to just read the actual size of the body once we have the whole thing.

**Comment by mfinelli** [comment]
Resolved in fd4d5e41f2f663a37828433701f9e95a715d9942
